# Generated by Django 5.2.6 on 2026-03-09 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcorrenteAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concorrente_nome', models.CharField(max_length=255)),
                ('texto_principal', models.TextField(blank=True)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('cta', models.CharField(blank=True, max_length=100)),
                ('plataforma', models.CharField(blank=True, default='Meta Ads', max_length=100)),
                ('link', models.URLField(blank=True)),
                ('data_referencia', models.DateField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_concorrentes', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Anúncio de Concorrente',
                'verbose_name_plural': 'Anúncios de Concorrentes',
                'ordering': ['-data_referencia', '-criado_em'],
            },
        ),
    ]
