# Generated by Django 5.2.6 on 2026-03-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concorrentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concorrentead',
            name='feed_cadencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='concorrentead',
            name='feed_datas_publicadas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='concorrentead',
            name='feed_formatos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='concorrentead',
            name='feed_posts_visiveis',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
