# Generated by Django 5.2.6 on 2026-03-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concorrentes', '0002_concorrentead_feed_cadencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concorrentead',
            name='feed_posts_detalhes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='concorrentead',
            name='posts_total_publicos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concorrentead',
            name='seguidores',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
