# Generated by Django 5.2.6 on 2026-03-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concorrentes', '0003_concorrentead_feed_posts_detalhes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concorrentead',
            name='ads_biblioteca_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concorrentead',
            name='ads_biblioteca_consultado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concorrentead',
            name='ads_biblioteca_query',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='concorrentead',
            name='ads_biblioteca_sinal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
