# Generated by Django 5.2.6 on 2026-03-09 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='campanhas/')),
                ('nome_referencia', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('periodo_tipo', models.CharField(choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual'), ('personalizado', 'Personalizado')], default='personalizado', max_length=20)),
                ('colunas_mapeadas_json', models.JSONField(blank=True, default=dict)),
                ('observacoes_importacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads_campanha', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Upload de Campanha',
                'verbose_name_plural': 'Uploads de Campanha',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CampanhaMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('campanha', models.CharField(max_length=255)),
                ('investimento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impressoes', models.BigIntegerField(default=0)),
                ('alcance', models.BigIntegerField(default=0)),
                ('cliques', models.BigIntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('cpc', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cpm', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('resultados', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cpl', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='campanhas.uploadcampanha')),
            ],
            options={
                'verbose_name': 'Métrica de Campanha',
                'verbose_name_plural': 'Métricas de Campanha',
                'ordering': ['campanha', 'data'],
            },
        ),
    ]
