# Generated by Django 5.2.6 on 2026-03-30 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_campanhametric_fingerprint'),
        ('empresas', '0010_configuracaouploadempresa_configuracao_analise_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPainel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='empresas/painel-uploads/')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('colunas_detectadas_json', models.JSONField(blank=True, default=list)),
                ('preview_json', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads_painel', to='empresas.configuracaouploadempresa')),
            ],
            options={
                'verbose_name': 'Upload de Painel',
                'verbose_name_plural': 'Uploads de Painel',
                'ordering': ['-criado_em'],
            },
        ),
    ]
