# Generated by Django 5.2.6 on 2026-03-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0003_uploadpainel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpainel',
            name='tipo_upload',
            field=models.CharField(blank=True, choices=[('', 'Não definido'), ('posts', 'Posts'), ('stories', 'Stories')], max_length=20),
        ),
    ]
