# Generated by Django 5.2.6 on 2026-04-05 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0004_uploadpainel_tipo_upload'),
        ('empresas', '0011_alter_configuracaouploadempresa_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPainel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=255)),
                ('data_evento', models.DateField()),
                ('impacto', models.CharField(choices=[('baixo', 'Baixo impacto'), ('medio', 'Médio impacto'), ('alto', 'Alto impacto')], max_length=10)),
                ('leads_media', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_painel', to='empresas.configuracaouploadempresa')),
            ],
            options={
                'verbose_name': 'Evento do Painel',
                'verbose_name_plural': 'Eventos do Painel',
                'ordering': ['-data_evento', '-pk'],
            },
        ),
    ]
