# Generated by Django 5.2.6 on 2026-04-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0005_eventopainel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadpainel',
            name='tipo_upload',
            field=models.CharField(blank=True, choices=[('', 'Não definido'), ('principal', 'Arquivo principal'), ('posts', 'Posts'), ('stories', 'Stories')], max_length=20),
        ),
    ]
