# Generated by Django 5.2.6 on 2026-03-09 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseConcorrencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Análise competitiva', max_length=255)),
                ('conteudo', models.TextField()),
                ('total_anuncios', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_concorrenciais', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Análise Concorrencial',
                'verbose_name_plural': 'Análises Concorrenciais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
