# Generated by Django 5.2.6 on 2026-03-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseconcorrencial',
            name='titulo',
            field=models.CharField(default='Análise dos Concorrentes', max_length=255),
        ),
    ]
