# Generated by Django 5.2.6 on 2026-03-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_alter_analiseconcorrencial_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiseconcorrencial',
            name='concorrente_nome',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
