# Generated by Django 5.2.6 on 2026-03-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ads_biblioteca_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ads_biblioteca_consultado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ads_biblioteca_query',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ads_biblioteca_sinal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='feed_cadencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='feed_datas_publicadas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='empresa',
            name='feed_formatos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='empresa',
            name='feed_posts_detalhes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='empresa',
            name='feed_posts_visiveis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instagram_profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='posts_total_publicos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='seguidores',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
