# Generated by Django 5.2.6 on 2026-03-23 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_ads_biblioteca_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoUploadEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('trafego_pago', 'Tráfego Pago'), ('eventos', 'Eventos'), ('vendas', 'Vendas'), ('leads', 'Leads'), ('crm', 'CRM'), ('financeiro', 'Financeiro'), ('estoque', 'Estoque'), ('atendimento', 'Atendimento')], max_length=40)),
                ('arquivo_exemplo', models.FileField(blank=True, upload_to='empresas/upload-configs/')),
                ('nome_arquivo_exemplo', models.CharField(blank=True, max_length=255)),
                ('colunas_detectadas_json', models.JSONField(blank=True, default=list)),
                ('preview_json', models.JSONField(blank=True, default=list)),
                ('mapeamento_json', models.JSONField(blank=True, default=dict)),
                ('campos_principais_json', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_upload', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuração de Upload',
                'verbose_name_plural': 'Configurações de Upload',
                'ordering': ['tipo_documento', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'tipo_documento'), name='unique_upload_config_per_company_and_type')],
            },
        ),
    ]
