# Generated by Django 5.2.6 on 2026-03-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_configuracaouploadempresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaouploadempresa',
            options={'ordering': ['nome', 'pk'], 'verbose_name': 'Configuração de Upload', 'verbose_name_plural': 'Configurações de Upload'},
        ),
        migrations.RemoveConstraint(
            model_name='configuracaouploadempresa',
            name='unique_upload_config_per_company_and_type',
        ),
        migrations.AlterField(
            model_name='configuracaouploadempresa',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('trafego_pago', 'Tráfego Pago'), ('eventos', 'Eventos'), ('vendas', 'Vendas'), ('leads', 'Leads'), ('crm', 'CRM'), ('financeiro', 'Financeiro'), ('estoque', 'Estoque'), ('atendimento', 'Atendimento')], max_length=40),
        ),
    ]
