# Generated by Django 5.2.6 on 2026-03-25 22:01

from django.db import migrations, models


def normalize_upload_types(apps, schema_editor):
    ConfiguracaoUploadEmpresa = apps.get_model('empresas', 'ConfiguracaoUploadEmpresa')
    ConfiguracaoUploadEmpresa.objects.filter(tipo_documento__in=['crm', 'vendas']).update(tipo_documento='crm_vendas')
    ConfiguracaoUploadEmpresa.objects.filter(tipo_documento__in=['leads', 'eventos']).update(tipo_documento='leads_eventos')


def reverse_normalize_upload_types(apps, schema_editor):
    ConfiguracaoUploadEmpresa = apps.get_model('empresas', 'ConfiguracaoUploadEmpresa')
    ConfiguracaoUploadEmpresa.objects.filter(tipo_documento='crm_vendas').update(tipo_documento='crm')
    ConfiguracaoUploadEmpresa.objects.filter(tipo_documento='leads_eventos').update(tipo_documento='leads')


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_configuracaouploadempresa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaouploadempresa',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('trafego_pago', 'Tráfego Pago'), ('crm_vendas', 'CRM Vendas'), ('leads_eventos', 'Leads Eventos')], max_length=40),
        ),
        migrations.RunPython(normalize_upload_types, reverse_normalize_upload_types),
    ]
