# Generated by Django 5.2.6 on 2026-03-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_configuracaouploadempresa_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
