# Generated by Django 5.2.6 on 2026-03-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_alter_configuracaouploadempresa_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaouploadempresa',
            name='configuracao_analise_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
