# Generated by Django 5.2.6 on 2026-04-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_configuracaouploadempresa_configuracao_analise_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaouploadempresa',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('trafego_pago', 'Tráfego Pago'), ('crm_vendas', 'Vendas'), ('leads_eventos', 'Leads Eventos'), ('redes_sociais', 'Redes Sociais')], max_length=40),
        ),
    ]
