# Generated by Django 5.2.6 on 2026-04-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_alter_configuracaouploadempresa_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaouploadempresa',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('trafego_pago', 'Ads Digital'), ('crm_vendas', 'Vendas'), ('leads_eventos', 'Presença Física'), ('redes_sociais', 'Presença Digital')], max_length=40),
        ),
    ]
