# Generated by Django 5.2.6 on 2026-03-09 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fim', models.DateField(blank=True, null=True)),
                ('tipo_periodo', models.CharField(choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual'), ('personalizado', 'Personalizado')], default='personalizado', max_length=20)),
                ('resumo_ia', models.TextField(blank=True)),
                ('insights_ia', models.TextField(blank=True)),
                ('html_renderizado', models.TextField(blank=True)),
                ('pdf_arquivo', models.FileField(blank=True, upload_to='relatorios/pdf/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-criado_em'],
            },
        ),
    ]
