# Generated by Django 5.2.6 on 2026-04-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='pdf_arquivo',
        ),
    ]
